### ISSUE TITLE
FR: option to publish the device availability topic as a binary sensor 

### ISSUE THREAD

**Issue by erkr** [dawidchyrzynski/arduino-home-assistant#206]
Hi,

Thanks for this great library. As an experiment I ported one of my projects (a board with 6 relays with both a MQTT and a web interface) to this library.  Reason: mainly the Discovery feature, my porjects require manual MQTT configurations.

In my projects I always configure the availability topic as a binary "connection" sensor. But in this library, that topic is not configured as a sensor for HA. I still have to add it manually like this:
```
binary_sensor:
  - name: connection
    unique_id: RELAIS_CTRL_166864_connection
    state_topic: "aha/RELAIS-CTRL_166864/avty_t"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity
    device:
      name: RELAIS-CTRL
      identifiers: 
       - RELAIS-CTRL_166864
```

It would be great when this binary_sensor could be added automatically via discovery as well

Best Eric
